"""Postgres schema + connection helper for the human review queue.

Two tables, deliberately asymmetric:
  - cases:   immutable mirror of the AI's output, seeded from
             data/audit_log.jsonl + a fresh matcher run. Never UPDATEd by
             the review app -- only ever inserted once per transaction_id,
             and re-seeding a changed record is rejected, not overwritten
             (see seed_review_queue.py).
  - reviews: append-only human decisions. A case's current status is
             derived by reading the latest review row, never stored
             directly on `cases`.

Runs against a local, dedicated Postgres container (see
postgres/docker-compose.yaml) -- free, local only, no cloud dependency,
and a completely separate server from Airflow's own internal Postgres
metadata store (airflow/) -- no cross-wiring between the two.

Note on transaction behavior: unlike SQLite, Postgres poisons the whole
transaction on the first error until ROLLBACK/close -- a statement can't
"partially fail" and let a later statement in the same transaction still
succeed. Nothing in this codebase currently tries to recover mid-transaction
after an error (every caller just lets the exception propagate to its
surrounding `finally: conn.close()`), so this is a non-issue today, but
worth remembering before adding a try/except around one statement inside a
longer transaction.
"""

import os

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

# Overridable so a second server instance can point at a completely
# separate database -- specifically for run_stream_simulator.py's demo
# mode, which must never touch the curated main database (603 real
# seeded cases, real LLM investigation results that took real time to
# produce, the one genuine auto-resolve), and for test_review_api.py's
# own ephemeral per-run database. Same schema, same code path, just a
# different database name on the same local Postgres server.
#
# This is the PRIVILEGED connection -- review_app is the container's own
# POSTGRES_USER (postgres/docker-compose.yaml), which the official
# Postgres image makes a superuser. Used for schema creation, migrations,
# seed_review_queue.py, one-off maintenance scripts, and test_review_api.py's
# CREATE/DROP DATABASE calls. The FastAPI app's own request handling does
# NOT use this connection -- see get_runtime_connection() below.
DATABASE_URL = os.environ.get(
    "REVIEW_QUEUE_DATABASE_URL",
    "postgresql://review_app:review_app_local_dev@localhost:5433/review_queue",
)

# The RESTRICTED connection main.py's request handlers actually use.
# Distinct, non-superuser role -- see ensure_runtime_role()'s own
# docstring for why review_app itself (a superuser) can't be the one
# this file's "cases: never UPDATEd by the review app" / "reviews:
# append-only" invariants are enforced against.
RUNTIME_ROLE = "review_app_runtime"
RUNTIME_ROLE_PASSWORD = os.environ.get(
    "REVIEW_QUEUE_RUNTIME_PASSWORD", "review_app_runtime_local_dev"
)

SCHEMA_VERSION = "1.0.0"

SCHEMA = """
CREATE TABLE IF NOT EXISTS cases (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id              TEXT UNIQUE NOT NULL,
    merchant_id                 TEXT,
    settlement_id               TEXT,
    matcher_exception_type      TEXT NOT NULL,
    agent_exception_type        TEXT NOT NULL,
    reclassified                INTEGER NOT NULL DEFAULT 0,
    agent_root_cause            TEXT,
    agent_recommended_action    TEXT,
    agent_confidence            DOUBLE PRECISION,
    agent_policy_id             TEXT,
    policy_id_consistent        INTEGER NOT NULL DEFAULT 0,
    agent_sufficient_evidence   INTEGER NOT NULL DEFAULT 0,
    gate_final_decision         TEXT NOT NULL,
    gate_reasons                TEXT NOT NULL,   -- JSON list
    gate_condition_checks       TEXT,             -- JSON list of {name, passed, detail}, one per
                                                     -- gate condition; NULL for entries seeded
                                                     -- before this field existed (see agent/gate.py)
    amount_at_risk_rupees       DOUBLE PRECISION NOT NULL
                                 CONSTRAINT cases_amount_at_risk_rupees_check CHECK (amount_at_risk_rupees >= 0),
    required_approval_tier      INTEGER NOT NULL
                                 CONSTRAINT cases_required_approval_tier_check CHECK (required_approval_tier IN (1, 2)),
    match_status                TEXT,
    match_pass                  TEXT,
    risk_class                  TEXT,
    ledger_expected_net_rupees  DOUBLE PRECISION,
    observed_net_rupees         DOUBLE PRECISION,
    net_delta_rupees            DOUBLE PRECISION,
    all_signals                 TEXT,             -- JSON list
    evidence_fields_cited       TEXT NOT NULL,    -- JSON list of {field, value, cited}
    provider                    TEXT,
    model                       TEXT,
    agent_run_id                TEXT,
    seeded_at                   TEXT NOT NULL,
    audit_log_source            TEXT NOT NULL,
    audit_record_hash           TEXT NOT NULL,
    schema_version               TEXT NOT NULL,

    -- Populated only when investigator/ (the multi-step tool-using agent)
    -- has a matching entry in data/investigation_log.jsonl for this
    -- transaction_id -- most cases won't have this, since investigator/
    -- runs on small hand-picked samples, not the full 603. NULL/0 means
    -- "not investigated," not "investigated and found nothing."
    investigated                         INTEGER NOT NULL DEFAULT 0,
    investigation_summary                TEXT,
    investigation_drafted_communication   TEXT,
    investigation_tool_rounds              INTEGER,
    investigation_log                       TEXT,   -- JSON list of {step, tool_name, arguments, result}
    investigation_source                     TEXT,
    investigation_gate_decision              TEXT,   -- the investigation's OWN gate outcome, may
                                                        -- differ from gate_final_decision above
    investigation_investigated_at            TEXT,   -- ISO timestamp, NULL for entries logged
                                                        -- before this field existed
    agent_decided_at                         TEXT    -- audit_log.jsonl's own "timestamp" field
);

CREATE TABLE IF NOT EXISTS reviews (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_uuid           TEXT UNIQUE NOT NULL,
    transaction_id        TEXT NOT NULL REFERENCES cases(transaction_id),
    reviewer_name         TEXT NOT NULL,
    reviewer_role         TEXT NOT NULL
                           CONSTRAINT reviews_reviewer_role_check CHECK (reviewer_role IN ('analyst', 'manager')),
    decision              TEXT NOT NULL
                           CONSTRAINT reviews_decision_check
                           CHECK (decision IN ('approved', 'overridden', 'escalated', 'reverted', 'auto_closed')),
    override_field        TEXT,
    override_old_value    TEXT,
    override_new_value    TEXT,
    notes                 TEXT,
    previous_status       TEXT,
    resulting_status      TEXT NOT NULL,
    created_at            TEXT NOT NULL,
    application_version   TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reviews_txn ON reviews(transaction_id, id);
"""


def get_connection() -> psycopg.Connection:
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def get_runtime_connection() -> psycopg.Connection:
    """The connection review_backend/main.py's request handlers actually
    use -- same host/port/dbname as DATABASE_URL (read fresh on every call,
    not cached, so it correctly follows test_review_api.py's per-run
    override of DATABASE_URL to an ephemeral test database), but a
    different, non-superuser role. See ensure_runtime_role()'s docstring
    for why this exists."""
    info = psycopg.conninfo.conninfo_to_dict(DATABASE_URL)
    info["user"] = RUNTIME_ROLE
    info["password"] = RUNTIME_ROLE_PASSWORD
    return psycopg.connect(psycopg.conninfo.make_conninfo(**info), row_factory=dict_row)


# Columns added after the DB was first created and seeded (603 real cases
# + hand-walked test reviews already in it) -- CREATE TABLE IF NOT EXISTS
# only helps a brand-new database. Migrating in place with
# ADD COLUMN IF NOT EXISTS preserves that existing data instead of
# requiring a wipe-and-reseed. (Postgres 9.6+ supports IF NOT EXISTS here,
# unlike SQLite -- no PRAGMA table_info introspection needed anymore.)
_MIGRATIONS = [
    ("investigated", "INTEGER NOT NULL DEFAULT 0"),
    ("investigation_summary", "TEXT"),
    ("investigation_drafted_communication", "TEXT"),
    ("investigation_tool_rounds", "INTEGER"),
    ("investigation_log", "TEXT"),
    ("investigation_source", "TEXT"),
    # The investigator runs its own copy of agent/gate.py, which can reach
    # a different verdict than whatever ended up primary for this case.
    # If investigator/'s result WAS available at first-seed time, it won
    # primary status (see resolution_source below) and this duplicates
    # gate_final_decision above. If a case was seeded before its
    # investigation existed, gate_final_decision stays frozen to the
    # original (possibly mock) agent/ proposal, and this column holds the
    # investigation's own separately-tracked outcome instead -- e.g.
    # trn-000237 was originally escalated by the $0 mock agent, but the
    # real investigator later gathered enough evidence to genuinely
    # auto-resolve it. NULL if no investigation exists.
    ("investigation_gate_decision", "TEXT"),
    ("investigation_investigated_at", "TEXT"),
    # The original agent run's own timestamp (audit_log.jsonl's "timestamp"
    # field) -- more accurate than `seeded_at` for an activity feed, since
    # seeded_at is when this row was INSERTed into review_backend's DB,
    # not when the AI actually made its decision (those can be far apart
    # if a case sits unseeded for a while).
    ("agent_decided_at", "TEXT"),
    # Structured per-condition PASS/FAIL breakdown (agent/gate.py's
    # gate_condition_checks) -- additive, same reasoning as every column
    # above. NULL for every case seeded before this field existed; the API/UI
    # must render that as "not available for this legacy entry", not "all
    # conditions failed".
    ("gate_condition_checks", "TEXT"),
    # 'agent' | 'investigator' -- which source's proposal actually became
    # this case's primary (agent_exception_type/agent_root_cause/etc. and
    # gate_final_decision above), decided ONCE at first-seed time by
    # seed_review_queue.py: investigator/'s multi-round investigation wins
    # if it already existed at that moment, else the single-shot agent/'s
    # proposal is used (and stays used, even if investigator/ catches up
    # later -- that's an enrichment, not a primary-proposal swap). NULL
    # for cases seeded before this column existed -- treat as 'agent',
    # since that was the only source before this change.
    ("resolution_source", "TEXT"),
]

# Same reasoning, applied to `reviews` instead of `cases` -- existing
# databases need ADD COLUMN, not just the CREATE TABLE IF NOT EXISTS above.
_REVIEWS_MIGRATIONS = [
    # The case's derived status immediately BEFORE this review event was
    # applied (resulting_status already stores the AFTER side). Makes every
    # event self-contained for audit -- no need to replay the whole prior
    # sequence just to know what a given transition actually changed. NULL
    # for rows written before this column existed. Found via external
    # review of the review-queue backend.
    ("previous_status", "TEXT"),
    # Hash-chained audit trail: sha256(prev row's chain_hash + this row's
    # own canonical fields), computed and stored at insert time in
    # submit_review() -- see review_backend/chain.py. Existing tamper
    # evidence in this project (seed_review_queue.py's _canonical_hash(),
    # audit_manifest.py) proves a single case's or a single run's content
    # is unaltered in isolation; neither proves the SEQUENCE of review
    # events is intact -- nothing stopped a row from being silently
    # deleted or reordered. A hash chain does: altering or removing any
    # historical row breaks verification for every row after it, not just
    # that one. NULL for rows written before this column existed --
    # verify_chain() in chain.py treats the oldest such row as a second
    # genesis point (a real, disclosed gap in coverage for pre-chain
    # history, not silently glossed over as if the chain reached back
    # further than it actually does).
    ("chain_hash", "TEXT"),
]


def _migrate(conn: psycopg.Connection) -> None:
    for col_name, col_def in _MIGRATIONS:
        conn.execute(f"ALTER TABLE cases ADD COLUMN IF NOT EXISTS {col_name} {col_def}")
    for col_name, col_def in _REVIEWS_MIGRATIONS:
        conn.execute(f"ALTER TABLE reviews ADD COLUMN IF NOT EXISTS {col_name} {col_def}")
    _migrate_reviews_decision_check(conn)


def _migrate_reviews_decision_check(conn: psycopg.Connection) -> None:
    """Unlike SQLite (which needs a full rename/copy/drop table rebuild to
    widen a CHECK constraint -- see git history for that ~95-line dance),
    Postgres supports altering a CHECK constraint directly. Cheap to
    re-run unconditionally on every startup at this row count (ADD
    CONSTRAINT validates existing rows, ~603 rows is instant)."""
    conn.execute("ALTER TABLE reviews DROP CONSTRAINT IF EXISTS reviews_decision_check")
    conn.execute("""
        ALTER TABLE reviews ADD CONSTRAINT reviews_decision_check
        CHECK (decision IN ('approved', 'overridden', 'escalated', 'reverted', 'auto_closed'))
    """)


def ensure_runtime_role(conn: psycopg.Connection) -> None:
    """Idempotently creates review_app_runtime, a restricted, non-superuser
    role for main.py's own request-handling connections -- distinct from
    the superuser role (review_app, DATABASE_URL) used for schema
    migrations, seeding, and one-off maintenance scripts.

    Why this exists: this file's own module docstring already states the
    invariant -- "cases: Never UPDATEd by the review app", "reviews:
    append-only" -- and grep confirms main.py's runtime queries really are
    SELECT/INSERT only, never UPDATE/DELETE. But until now that promise
    was enforced purely by application-code discipline: review_app (the
    container's own POSTGRES_USER) is a Postgres superuser, and
    superusers bypass BOTH `REVOKE` and Row-Level Security, by Postgres
    design -- confirmed against Postgres's own documented semantics
    before writing any of this, not assumed. A future bug in main.py
    could silently violate the append-only invariant and nothing in the
    database would object; chain.py's hash chain would only prove it
    happened after the fact.

    review_app_runtime is a genuinely different, non-owning, non-superuser
    role, so both layers below actually take effect for it (unlike for
    review_app itself): UPDATE/DELETE are explicitly revoked, and Row-Level
    Security additionally blocks them -- belt-and-suspenders, the same
    shape this project's own citation-validity gate already uses
    elsewhere. A REVOKE/RLS migration applied to review_app alone would
    have been silently inert against this project's existing role setup,
    since review_app is a superuser and superusers bypass RLS/REVOKE
    regardless. The separate, non-superuser runtime role is not optional
    ceremony; it is the part that makes the control real.

    Runs on every init_db() call (schema creation, every test run, every
    server startup) -- idempotent throughout: role creation checks
    pg_roles first, GRANT/REVOKE are safe to repeat, and the RLS policies
    are dropped and recreated rather than assumed absent."""
    conn.execute(
        sql.SQL("""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = {role}) THEN
                    EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L', {role}, {password});
                ELSE
                    EXECUTE format('ALTER ROLE %I WITH PASSWORD %L', {role}, {password});
                END IF;
            END
            $$;
        """).format(role=sql.Literal(RUNTIME_ROLE), password=sql.Literal(RUNTIME_ROLE_PASSWORD))
    )

    conn.execute(sql.SQL("GRANT SELECT, INSERT ON cases, reviews TO {}").format(sql.Identifier(RUNTIME_ROLE)))
    conn.execute(sql.SQL("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {}").format(sql.Identifier(RUNTIME_ROLE)))
    conn.execute(sql.SQL("REVOKE UPDATE, DELETE ON cases, reviews FROM {}").format(sql.Identifier(RUNTIME_ROLE)))

    for table in ("cases", "reviews"):
        table_id = sql.Identifier(table)
        conn.execute(sql.SQL("ALTER TABLE {} ENABLE ROW LEVEL SECURITY").format(table_id))
        conn.execute(sql.SQL("ALTER TABLE {} FORCE ROW LEVEL SECURITY").format(table_id))
        for policy, clause in (("select", "FOR SELECT USING (true)"),
                                ("insert", "FOR INSERT WITH CHECK (true)"),
                                ("no_update", "FOR UPDATE USING (false)"),
                                ("no_delete", "FOR DELETE USING (false)")):
            policy_name = sql.Identifier(f"{table}_{policy}_policy")
            conn.execute(sql.SQL("DROP POLICY IF EXISTS {} ON {}").format(policy_name, table_id))
            conn.execute(
                sql.SQL("CREATE POLICY {} ON {} " + clause).format(policy_name, table_id)
            )


def init_db() -> None:
    conn = get_connection()
    try:
        conn.execute(SCHEMA)
        _migrate(conn)
        ensure_runtime_role(conn)
        conn.commit()
    finally:
        conn.close()


if __name__ == "__main__":
    init_db()
    print(f"Initialized {DATABASE_URL}")
