"""
One-command demo launcher -- run this, and only this, during the demo.

Verifies the environment, runs the deterministic pipeline live (it's fast
and provable -- 2,000+ transactions in ~1 second, no LLM), makes sure the
review queue is seeded, then starts the local server and prints the two
URLs to open.

Deliberately does NOT call any LLM. Every LLM-dependent artifact
(data/audit_log.jsonl, data/investigation_log.jsonl, the RAG ablation CSV)
is a logged result from an earlier real run -- this script surfaces those
logs, it never regenerates them. That keeps demo-day startup at a few
seconds and removes any dependency on Ollama being up while presenting.

    python run_demo.py
    python run_demo.py --port 8000
    python run_demo.py --skip-server     # checks + pipeline only, no server
    python run_demo.py --live-case       # ALSO sends one real, live case through the
                                          # investigator before starting the server -- for
                                          # recording a genuine "watch the AI work" moment.
                                          # Needs Ollama already running (you start it
                                          # yourself); everything else here still makes
                                          # zero other LLM calls.
    python run_demo.py --live-case --live-case-id trn-000001   # a specific case instead
                                                                 # of the next un-investigated one

Ctrl+C stops the server.
"""

import os
import sys
import json
import argparse
import subprocess

# The matcher's own summary and any LLM-generated text can contain a rupee
# sign (U+20B9); Windows consoles default to cp1252 and crash on it.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(ROOT, "data")
REACT_APP_INDEX = os.path.join(ROOT, "ui", "review-queue-app", "dist", "index.html")

# Generated by Layer 1; without these nothing downstream can run.
REQUIRED_DATA = ["gateway.json", "bank_statement.csv", "internal_settlement_ledger.csv"]

# Produced by earlier real LLM runs. Missing ones degrade the demo but
# don't break it, so they're reported as warnings, never as failures.
OPTIONAL_ARTIFACTS = {
    "audit_log.jsonl": "run_agent.py --mode full",
    "investigation_log.jsonl": "run_investigator.py --transaction-id <id>",
    "rag_ablation_detail.csv": "run_rag_ablation.py",
}


def fail(msg: str, fix: str) -> None:
    print(f"\n  FAILED: {msg}")
    print(f"  Fix:    {fix}\n")
    raise SystemExit(1)


def check_environment() -> None:
    print("=" * 70)
    print("1. ENVIRONMENT")
    print("=" * 70)

    # The single most common failure on this machine: running under the
    # global Python (no fastapi/uvicorn) instead of the project's .venv.
    in_venv = sys.prefix != sys.base_prefix
    print(f"Python:      {sys.executable}")
    if not in_venv:
        fail("not running inside the project virtualenv",
             ".venv/Scripts/python.exe run_demo.py")

    try:
        import fastapi  # noqa: F401
        import uvicorn  # noqa: F401
        import pandas   # noqa: F401
        import psycopg  # noqa: F401
    except ImportError as e:
        fail(f"missing dependency: {e.name}",
             ".venv/Scripts/python.exe -m pip install -r requirements.txt")
    print("Deps:        fastapi, uvicorn, pandas, psycopg all importable")

    # The review queue's data now lives in Postgres (postgres/docker-compose.yaml),
    # not a SQLite file -- a real, cheap, one-shot connection attempt here
    # gives a clear fix-it message up front instead of a raw psycopg
    # traceback surfacing later, mid-seed or mid-server-start.
    from review_backend import db as review_db
    try:
        conn = psycopg.connect(review_db.DATABASE_URL, connect_timeout=2)
        conn.close()
        print("Postgres:    reachable")
    except psycopg.OperationalError as e:
        fail(f"can't reach the review queue's Postgres database: {e}",
             "docker compose -f postgres/docker-compose.yaml up -d")

    missing = [f for f in REQUIRED_DATA if not os.path.exists(os.path.join(DATA_DIR, f))]
    if missing:
        fail(f"missing generated data: {', '.join(missing)}",
             "python generate_data.py")
    print(f"Data:        {len(REQUIRED_DATA)} source files present")

    if not os.path.exists(REACT_APP_INDEX):
        fail("review queue React app hasn't been built (dist/ missing)",
             "cd ui/review-queue-app && npm install && npm run build")
    print("Review UI:   ui/review-queue-app/dist/ present")

    for name, how in OPTIONAL_ARTIFACTS.items():
        path = os.path.join(DATA_DIR, name)
        if os.path.exists(path):
            print(f"             {name} present")
        else:
            print(f"             [warn] {name} missing -- some panels will be empty ({how})")
    # Stated explicitly, not left implicit in a docstring only a reader of
    # the source would see -- following an external review noting a judge
    # running `python run_demo.py` could reasonably expect the full AI
    # pipeline to regenerate live. It doesn't: every LLM-dependent artifact
    # shown below is a logged result from an earlier real run.
    print("AI artifacts: using previously generated, audited LLM results")
    print("LLM calls this run: 0 (use --live-case to also send one real case through the")
    print("                       investigator, which needs Ollama running)")
    print()


def run_pipeline() -> dict:
    """Runs the deterministic layers live. This is the part worth doing on
    stage: it's genuinely fast, and it proves the numbers on the dashboard
    are produced by code, not typed into HTML."""
    print("=" * 70)
    print("2. DETERMINISTIC PIPELINE (live, no LLM)")
    print("=" * 70)

    from evaluate import evaluate

    results = evaluate_quietly(evaluate)

    print(f"Transactions reconciled:     {results['transactions_processed']:,}")
    print(f"Elapsed:                     {results['matcher_elapsed_seconds']}s "
          f"(~{results['matcher_txns_per_second']:,} txn/s)")
    print(f"Settlement-aware accuracy:   {results['settlement_aware_accuracy_pct']}%")
    print(f"False auto-resolve rate:     {results['false_auto_resolve_rate_pct']}% "
          f"({results['false_auto_resolve_count']}/{results['transactions_processed']})")
    print(f"Hard negatives handled:      {results['hard_negatives_correct']}/"
          f"{results['hard_negatives_total']}")
    print()
    return results


def evaluate_quietly(evaluate_fn) -> dict:
    """evaluate() prints its own full multi-section report, which is great
    standalone but drowns the demo launcher's output. Capture it and keep
    only the returned numbers -- the full report stays one command away
    (python evaluate.py) if a judge asks to see the workings."""
    import io
    import contextlib
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        results = evaluate_fn()
    return results


def ensure_seeded() -> None:
    print("=" * 70)
    print("3. REVIEW QUEUE")
    print("=" * 70)

    audit_log = os.path.join(DATA_DIR, "audit_log.jsonl")
    if not os.path.exists(audit_log):
        print("[warn] no audit_log.jsonl -- the review queue will be empty.")
        print("       Run: python run_agent.py --mode full   (needs an LLM provider)")
        print()
        return

    from seed_review_queue import seed
    result = seed()
    print(f"Escalated cases in audit log: {result['escalated_in_audit_log']}")
    print(f"Newly inserted:               {result['inserted']}")
    print(f"Already seeded, unchanged:    {result['unchanged']}")
    print(f"Enriched with investigation:  {result['enriched_with_investigation']}")
    if result["conflicts"]:
        print(f"[warn] {len(result['conflicts'])} case(s) conflicted and were left untouched "
              f"(by design -- see seed_review_queue.py)")
    print()


def _ollama_reachable(host: str) -> bool:
    try:
        import requests
        requests.get(f"{host}/api/tags", timeout=3)
        return True
    except Exception:  # noqa: BLE001 -- any failure here just means "not reachable"
        return False


def _pick_live_case(report, transaction_id: str | None):
    """The specified transaction_id if given (must be a real escalated
    case), otherwise the first escalated case with no real investigation
    on record yet -- so re-running this for a second take of the video
    picks a genuinely fresh case each time instead of re-investigating
    the same one. Total-infra-failure placeholders (Ollama was down on a
    prior attempt) don't count as "already investigated"."""
    from evaluate_investigator import load_good_investigations, LOG_PATH

    escalated = report[report["final_exception_type"].notna() & (~report["auto_resolve_eligible"])]

    if transaction_id:
        match = escalated[escalated["transaction_id"] == transaction_id]
        if match.empty:
            fail(f"'{transaction_id}' is not an escalated case",
                 "pick a transaction_id from the review queue, or drop --live-case-id")
        return match.iloc[0]

    already_investigated = load_good_investigations(LOG_PATH)
    remaining = escalated[~escalated["transaction_id"].isin(already_investigated)]
    if remaining.empty:
        fail("every escalated case already has a real investigation on record",
             "pass --live-case-id <transaction_id> to re-run one on purpose")
    return remaining.iloc[0]


def send_live_case(port_hint: int, transaction_id: str | None = None) -> None:
    """Sends exactly ONE case through the real, multi-step investigation
    agent -- the only place in this whole launcher that makes a live LLM
    call, and only when --live-case is explicitly passed. Meant to be run
    right before you hit record: the terminal shows the real tool-call
    trace as it happens, then the case shows up freshly tagged
    INVESTIGATED in the review queue once the server starts."""
    print("=" * 70)
    print("LIVE CASE -- sending one real case through the investigation agent")
    print("=" * 70)

    from investigator import config as inv_config
    if not _ollama_reachable(inv_config.OLLAMA_HOST):
        fail(f"Ollama not reachable at {inv_config.OLLAMA_HOST}",
             "start Ollama yourself (this script never starts it for you), "
             "confirm `ollama list` shows the model, then re-run with --live-case")

    from run_matcher import run as run_matcher
    from matching.loaders import load_sources
    from agent.policy_kb import get_policy
    from agent.evidence import build_evidence, build_policy_block
    from agent.gate import apply_gate
    from investigator.tools import ToolContext
    from investigator.loop import investigate, tool_evidence_ids
    from investigator.ollama_client import OllamaToolClient
    from run_investigator import print_case_trace, LOG_PATH as INVESTIGATION_LOG_PATH
    import datetime as dt

    report, settlement_matches, _ = run_matcher(DATA_DIR)
    gateway, bank, ledger = load_sources(DATA_DIR)
    row = _pick_live_case(report, transaction_id)
    row_dict = row.to_dict()

    print(f"Case: {row_dict['transaction_id']} ({row_dict['final_exception_type']})")
    print(f"Model: {inv_config.INVESTIGATOR_MODEL} via {inv_config.OLLAMA_HOST}")
    print("This runs a real multi-step investigation -- several minutes on CPU-only")
    print("Ollama, up to 6 tool-call rounds. The trace below is happening live.")
    print()

    exc_type = row_dict["final_exception_type"]
    try:
        policy = get_policy(exc_type)
        policy_block = build_policy_block(policy, policy["policy_id"])
    except KeyError:
        policy_block = "[NO MATCHING POLICY FOUND -- treat as insufficient evidence.]"
    evidence_block = build_evidence(row_dict)

    ctx = ToolContext(report, gateway, bank, settlement_matches)
    client = OllamaToolClient()
    result = investigate(row_dict, policy_block, evidence_block, ctx, client)
    gate_result = apply_gate(result, row_dict, tool_evidence_ids(result))

    print_case_trace(row_dict, result, gate_result)

    entry = {"transaction_id": row_dict["transaction_id"], **result.model_dump(),
             "gate_decision": gate_result["final_decision"],
             "gate_agent_status": gate_result["agent_status"],
             "model": client.model,
             "investigated_at": dt.datetime.now(dt.timezone.utc).isoformat()}
    with open(INVESTIGATION_LOG_PATH, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, default=str) + "\n")
    print(f"Appended to {INVESTIGATION_LOG_PATH}")

    from seed_review_queue import seed
    seed_result = seed()
    print(f"Review queue re-seeded: {seed_result['enriched_with_investigation']} case(s) "
          f"newly enriched with this investigation.")
    print(f"Open http://127.0.0.1:{port_hint}/review-queue/ and search "
          f"{row_dict['transaction_id']} to show it live.")
    print()


def start_server(port: int) -> None:
    print("=" * 70)
    print("4. DEMO SERVER")
    print("=" * 70)
    print(f"  Dashboard     http://127.0.0.1:{port}/showcase.html")
    print(f"  Review queue  http://127.0.0.1:{port}/review-queue/")
    print()
    print("  One process serves both the API and the static UI -- no CORS, no hosting.")
    print("  Ctrl+C to stop.")
    print("=" * 70)
    print()

    try:
        subprocess.run(
            [sys.executable, "-m", "uvicorn", "review_backend.main:app",
             "--host", "127.0.0.1", "--port", str(port)],
            cwd=ROOT,
        )
    except KeyboardInterrupt:
        print("\nServer stopped.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--skip-server", action="store_true",
                         help="run the checks and pipeline, but don't start the server")
    parser.add_argument("--live-case", action="store_true",
                         help="send one real, live case through the investigation agent "
                              "before starting the server (needs Ollama already running)")
    parser.add_argument("--live-case-id", default=None,
                         help="with --live-case, investigate this specific transaction_id "
                              "instead of the next un-investigated one")
    args = parser.parse_args()

    print()
    print("  AI FINANCE CONTROLLER -- Razorpay Buildathon, Track 04")
    print("  Reconciliation, exception handling, and cash position, fully local.")
    print()

    check_environment()
    run_pipeline()
    ensure_seeded()

    if args.live_case:
        send_live_case(args.port, args.live_case_id)

    if args.skip_server:
        print("Checks complete (--skip-server given, not starting the server).")
        return
    start_server(args.port)


if __name__ == "__main__":
    main()
